### PR TITLE
Localize times

### PR DESCRIPTION
**Pull request by gavinmorrow**
# Localize timestamps
- Adds a setting to the config called `timezone_offset`. 
  - It is composed of three integers (positive or negative) separated by dots (`.`)
    - e.g. `-5.0.0` is EST. 
- Updates the timestamps of messages to be offset by that amount. 

# Todo
- Automatically detect time zone from system.

### CODE REVIEW

**Comment by Garmelon** [comment]
Thanks for the PR.

You seem to be using code that can panic when it shouldn't and a weird autoformatter that obscures the actual changes made in the diff. Cove uses standard rustfmt, so maybe try running `cargo fmt`?

With cove in general, I try to do things "the right way". For time zones, this includes using the system time zones (i.e. not requiring recompilation if time zones change) and supporting DST. However, for those platforms where no good libraries exist, a constant offset option might be a good fallback.

In any case, before I merge something like this, I first want to have another look at time zones and related libraries, and plan out a design that can handle the above requirements.

**Comment by Garmelon** [comment]
The [tz crate](https://crates.io/crates/tz-rs) might fulfill the requirements on unix-y platforms. On windows, people could provide their own copy of the tz database or use a constant offset.

The nice thing about this is that we could use an existing standard, the format of the `TZ` environment variable, to configure both static offsets and link to tz data files. See also [`TimeZone::from_posix_tz`](https://docs.rs/tz-rs/0.6.14/tz/struct.TimeZone.html#method.from_posix_tz).

**Comment by gavinmorrow** [comment]
I fixed the formatting, and I'll try to get to the other stuff soon.

**Comment by Garmelon** [comment]
You don't need to fix this PR, I'm already working on a different way to support time zones using the tz crate.

**Comment by Garmelon** [comment]
11 months later... Cove v0.8.0 now has time zone support.

**Pull request closed without merging**
